### PR TITLE
It had to be done

### PR DESCRIPTION
**Pull request by markryd**

### CODE REVIEW

**Comment by becdetat** [comment]
I sooooooooo want to merge this.

**Comment by markryd** [comment]
I'm disappointed I could think of a better Wreck API.

```
//as an exception override?
Check.Yourself(x => x.FirstName).IsNotNull().WreckYourself(x => new DerpException(x.Error)); 
```

**Comment by markryd** [comment]
The world wasn't ready.

**Comment by becdetat** [comment]
image

**Pull request closed without merging**
